name: Run Multiple Scripts Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC

jobs:
  run-multiple:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: live

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Multiple Scripts
        run: |
          cd FYP_Scraper && scrapy crawl city42
          cd FYP_Scraper && scrapy crawl dailypakistan
          cd FYP_Scraper && scrapy crawl urdupoint_multi_category -a selected_category=murder
          cd FYP_Scraper && scrapy crawl urdupoint_multi_category -a selected_category=thief
          cd FYP_Scraper && scrapy crawl urdupoint_multi_category -a selected_category=robbery
          cd FYP_Scraper && scrapy crawl urdupoint_multi_category -a selected_category=accident
          cd FYP_Scraper && scrapy crawl urdupoint_multi_category -a selected_category=terrorism
          cd FYP_Scraper && scrapy crawl urdupoint_multi_category -a selected_category=kidnapping
          cd FYP_Scraper && scrapy crawl urdupoint_multi_category -a selected_category=rape
          cd FYP_Scraper && scrapy crawl urdupoint_multi_category -a selected_category=suicide
          
          cd FYP_Scraper && scrapy crawl nawaiwaqt
          cd FYP_Scraper && scrapy crawl 24_news
